[package]
name = "behemoth"
version = "0.3.1"
authors = ["Sean Leffler <sean@errno.com>"]

[features]
default = ["matrix_rand", "vector_rand"]
matrix_rand = ["rand"]
vector_rand = ["rand"]

[dependencies]
rand = { version = "0.3", optional = true }
