[package]
name = "behemoth"
version = "0.3.1"
authors = ["Sean Leffler <sean@errno.com>"]

[features]
default = ["lowdim_special_cases", "matrix_rand", "vector_rand"]
lowdim_special_cases = []
matrix_rand = ["rand"]
vector_rand = ["rand"]

[dependencies]
rand = { version = "0.3", optional = true }
